// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UltimateMessengerSuggestions.DbContexts;

#nullable disable

namespace UltimateMessengerSuggestions.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250712162947_AlterFindMediaByTagsProcedure")]
    partial class AlterFindMediaByTagsProcedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MediaFileTag", b =>
                {
                    b.Property<int>("MediaFilesId")
                        .HasColumnType("integer")
                        .HasColumnName("media_files_id");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer")
                        .HasColumnName("tags_id");

                    b.HasKey("MediaFilesId", "TagsId")
                        .HasName("pk_media_file_tag");

                    b.HasIndex("TagsId")
                        .HasDatabaseName("ix_media_file_tag_tags_id");

                    b.ToTable("media_file_tag", (string)null);
                });

            modelBuilder.Entity("UltimateMessengerSuggestions.Models.Db.MediaFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean")
                        .HasColumnName("is_public");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_url");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("public_id");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_media_files_owner_id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_media_files_public_id");

                    b.ToTable("media_files", null, t =>
                        {
                            t.HasCheckConstraint("CK_Message_Type", "\"media_type\" IN ('voice', 'picture')");
                        });

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("UltimateMessengerSuggestions.Models.Db.MessengerAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client");

                    b.Property<string>("MessengerId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("messenger_id");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_messenger_accounts");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_messenger_accounts_user_id");

                    b.ToTable("messenger_accounts", (string)null);
                });

            modelBuilder.Entity("UltimateMessengerSuggestions.Models.Db.ProcedureData.MediaFileSearchResult", b =>
                {
                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Discriminator")
                        .HasColumnType("text")
                        .HasColumnName("discriminator");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_type");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("media_url");

                    b.Property<int?>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.Property<string>("TagName")
                        .HasColumnType("text")
                        .HasColumnName("tag_name");

                    b.Property<string>("VkConversation")
                        .HasColumnType("text")
                        .HasColumnName("vk_conversation");

                    b.Property<long?>("VkMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("vk_message_id");

                    b.ToTable("media_file_search_results", (string)null);
                });

            modelBuilder.Entity("UltimateMessengerSuggestions.Models.Db.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tags");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_tags_name");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("UltimateMessengerSuggestions.Models.Db.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("UserHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("UltimateMessengerSuggestions.Models.Db.VkVoiceMediaFile", b =>
                {
                    b.HasBaseType("UltimateMessengerSuggestions.Models.Db.MediaFile");

                    b.Property<string>("VkConversation")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vk_conversation");

                    b.Property<long>("VkMessageId")
                        .HasColumnType("bigint")
                        .HasColumnName("vk_message_id");

                    b.ToTable("vk_voice_media_file", null, t =>
                        {
                            t.HasCheckConstraint("CK_Message_Type", "\"media_type\" IN ('voice', 'picture')");
                        });
                });

            modelBuilder.Entity("MediaFileTag", b =>
                {
                    b.HasOne("UltimateMessengerSuggestions.Models.Db.MediaFile", null)
                        .WithMany()
                        .HasForeignKey("MediaFilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_file_tag_media_files_media_files_id");

                    b.HasOne("UltimateMessengerSuggestions.Models.Db.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_file_tag_tags_tags_id");
                });

            modelBuilder.Entity("UltimateMessengerSuggestions.Models.Db.MediaFile", b =>
                {
                    b.HasOne("UltimateMessengerSuggestions.Models.Db.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_files_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("UltimateMessengerSuggestions.Models.Db.MessengerAccount", b =>
                {
                    b.HasOne("UltimateMessengerSuggestions.Models.Db.User", "User")
                        .WithMany("MessengerAccounts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_messenger_accounts_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UltimateMessengerSuggestions.Models.Db.VkVoiceMediaFile", b =>
                {
                    b.HasOne("UltimateMessengerSuggestions.Models.Db.MediaFile", null)
                        .WithOne()
                        .HasForeignKey("UltimateMessengerSuggestions.Models.Db.VkVoiceMediaFile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vk_voice_media_file_media_files_id");
                });

            modelBuilder.Entity("UltimateMessengerSuggestions.Models.Db.User", b =>
                {
                    b.Navigation("MessengerAccounts");
                });
#pragma warning restore 612, 618
        }
    }
}
